version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - chetam

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    networks:
      - chetam
    volumes:
      - /mnt/postgress_db:/var/lib/postgresql/data

networks:
  chetam:
    driver:
      bridge

volumes:
  postgres_data:
