CREATE TABLE users
(
    id         SERIAL PRIMARY KEY,
    login      VARCHAR(100) UNIQUE NOT NULL,
    phone      VARCHAR(100) UNIQUE,
    email      VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(100)        NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);