// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"chetam/internal/service"
)

// Injectors from wire.go:

func InitializeChetam() (chetam.Chetam, error) {
	logger := provideSlog()
	service, err := provideAuthService()
	if err != nil {
		return chetam.Chetam{}, err
	}
	chetamFetcher, err := provideChetamFetcher()
	if err != nil {
		return chetam.Chetam{}, err
	}
	chetamChetam := provideChetam(logger, service, chetamFetcher)
	return chetamChetam, nil
}
